// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using dotNET_Test.PageObjects;

namespace dotNET_Test.TestClasses {
[TestFixture]
public class Tests  : BasePage {

  

  [OneTimeSetUp]
  public void SetUp() {
    Initialize();
  }


  
  [Test]
  public void test_succes_add_item() {
    HomePage homepage = new HomePage(driver);
    homepage.addToBasket();
    Thread.Sleep(1000);
    Assert.That(driver.FindElement(By.CssSelector(".site-header__cart > .small--hide")).Text, Is.EqualTo("Sepetiniz (1)"));
  }

  [Test]
  public void test_empty_basket() {
    HomePage homepage = new HomePage(driver);
    BasketPage basketpage = new BasketPage(driver);
    homepage.addToBasket();
    Thread.Sleep(3000);
    homepage.goToBasket();
    basketpage.remove_from_basket();
    
    Assert.That(basketpage.check_item_number_at_basket(), Is.EqualTo("0")); 
  }

  [Test]
  public void test_change_quantity() {
    HomePage homepage = new HomePage(driver);
    BasketPage basketpage = new BasketPage(driver);
    homepage.addToBasket();
    Thread.Sleep(1000);
    homepage.goToBasket();
    String newItemQuantity = "5";
    basketpage.change_item_quantity(newItemQuantity);
    Thread.Sleep(2000);
    Assert.That(basketpage.check_item_number_at_basket(), Is.EqualTo(newItemQuantity)); 

  }





  [OneTimeTearDown]
  protected void Close() {
  TearDown();
  }
}
}